### ISSUE TITLE
Adjustable pramaters for the "nose down" beep rate

### ISSUE THREAD

**Issue by MalicT** [Uriei/EDPlanetBearing#11]
Give the user an ability to change where you get the quick "nose down" series of beeps so they can tune for their ship performance, or if the pitch rate of the ship is put into the journal, ability to grab that and factor in rate, and then a variable reaction time factor for the user

**Comment by Uriei** [comment]
I'll think on that, if so, I'd include it within this https://github.com/Uriei/EDPlanetBearing/issues/12

**Comment by Uriei** [comment]
Moved to: https://gitlab.com/uriei/EDPlanetBearing/issues/11
